DROP TABLE IF EXISTS hemnet_items;

DROP TABLE IF EXISTS hemnet_comp_items;

DROP TABLE IF EXISTS houm_favorites;

DROP TABLE IF EXISTS houm_users;

--
--
CREATE TABLE hemnet_items (
    id BIGSERIAL PRIMARY KEY,
    hemnet_id BIGINT,
    -- indexed
    url VARCHAR,
    listing_url VARCHAR,
    broker_name VARCHAR DEFAULT '',
    broker_phone VARCHAR DEFAULT '',
    broker_email VARCHAR DEFAULT '',
    -- indexed
    broker_firm VARCHAR,
    broker_firm_phone VARCHAR,
    sold_date DATE,
    price_per_square_meter FLOAT,
    price INTEGER,
    asked_price INTEGER,
    price_trend_flat INTEGER,
    price_trend_percentage INTEGER,
    rooms FLOAT,
    monthly_fee INTEGER,
    square_meters FLOAT,
    cost_per_year INTEGER,
    year VARCHAR DEFAULT '',
    type VARCHAR DEFAULT '',
    association VARCHAR,
    lot_size INTEGER,
    biarea INTEGER,
    address VARCHAR DEFAULT '',
    geographic_area VARCHAR DEFAULT '',
    latitude FLOAT,
    longitude FLOAT,
    collected_at DATE,
    -- defaults to datetime.now() but stored as DATE
    title VARCHAR,
    description TEXT,
    housing_form VARCHAR,
    tenure VARCHAR,
    days_on_hemnet INTEGER,
    is_new_construction BOOLEAN,
    is_project BOOLEAN,
    is_project_unit BOOLEAN,
    is_upcoming BOOLEAN,
    is_foreclosure BOOLEAN,
    is_bidding_ongoing BOOLEAN,
    bidding_started BOOLEAN,
    published_at TIMESTAMP,
    times_viewed INTEGER,
    verified_bidding JSONB,
    listing_broker_url VARCHAR,
    listing_broker_gallery_url VARCHAR,
    post_code VARCHAR,
    municipality_name VARCHAR,
    region_name VARCHAR,
    county_name VARCHAR,
    districts JSONB,
    labels JSONB,
    relevant_amenities JSONB,
    listing_collection_ids JSONB,
    breadcrumbs JSONB,
    ad_targeting JSONB,
    attachments JSONB,
    images JSONB,
    images_preview JSONB,
    thumbnail JSONB,
    photo_attribution JSONB,
    price_change JSONB,
    upcoming_open_houses JSONB,
    floor_plan_images JSONB,
    video_attachment JSONB,
    three_d_attachment JSONB,
    energy_classification JSONB,
    active_package JSONB,
    seller_package_recommendation JSONB,
    housing_cooperative JSONB,
    housing_cooperative_name VARCHAR,
    yearly_arrende_fee INTEGER,
    yearly_leasehold_fee INTEGER,
    land_area FLOAT,
    formatted_land_area VARCHAR,
    formatted_living_area VARCHAR,
    formatted_supplemental_area VARCHAR,
    supplemental_area FLOAT,
    formatted_floor VARCHAR,
    closest_water_distance_meters INTEGER,
    coastline_distance_meters INTEGER,
    raw_listing JSONB,
    raw_apollo_state JSONB,
    broker_raw JSONB,
    broker_agency_raw JSONB,
    main_image_url VARCHAR,
    main_image_bytes BYTEA,
    main_image_mime VARCHAR,
    floorplan_image_url VARCHAR,
    floorplan_image_bytes BYTEA,
    floorplan_image_mime VARCHAR
);

CREATE TABLE hemnet_comp_items (
    id BIGSERIAL PRIMARY KEY,
    salda_id BIGINT,
    -- indexed
    hemnet_id BIGINT,
    -- indexed
    url VARCHAR,
    lattitude FLOAT,
    longitude FLOAT,
    city VARCHAR,
    postal_city VARCHAR,
    district VARCHAR,
    country VARCHAR,
    region VARCHAR,
    municipality VARCHAR,
    street VARCHAR,
    location VARCHAR,
    main_location VARCHAR,
    street_address VARCHAR,
    offers_selling_price BOOLEAN,
    living_area FLOAT,
    rooms FLOAT,
    broker_firm VARCHAR,
    new_production BOOLEAN,
    upcoming_open_houses BOOLEAN DEFAULT false,
    home_swapping BOOLEAN,
    has_price_change BOOLEAN,
    has_active_toplisting BOOLEAN,
    status VARCHAR,
    price INTEGER,
    cost_per_year INTEGER,
    monthly_fee INTEGER,
    publication_date DATE,
    images_count INTEGER,
    item_type VARCHAR,
    price_per_m2 INTEGER,
    collected_at DATE
);

CREATE TABLE houm_users (
    id BIGSERIAL PRIMARY KEY,
    name VARCHAR NOT NULL,
    name_key VARCHAR NOT NULL UNIQUE,
    min_price INTEGER,
    max_price INTEGER,
    min_rooms FLOAT,
    max_rooms FLOAT,
    min_area FLOAT,
    max_area FLOAT,
    min_year INTEGER,
    max_year INTEGER,
    max_monthly_fee INTEGER,
    housing_forms JSONB,
    tenure JSONB,
    municipalities JSONB,
    regions JSONB,
    districts JSONB,
    prefer_new_construction BOOLEAN,
    prefer_upcoming BOOLEAN,
    max_coast_distance_m INTEGER,
    max_water_distance_m INTEGER,
    created_at TIMESTAMP DEFAULT NOW(),
    updated_at TIMESTAMP DEFAULT NOW()
);

CREATE TABLE houm_favorites (
    user_id BIGINT NOT NULL REFERENCES houm_users(id) ON DELETE CASCADE,
    hemnet_id BIGINT NOT NULL,
    created_at TIMESTAMP DEFAULT NOW(),
    PRIMARY KEY (user_id, hemnet_id)
);
