# -*- coding: utf-8 -*-

# Define here the models for your scraped items
#
# See documentation in:
# http://doc.scrapy.org/en/latest/topics/items.html

import scrapy


class HemnetItem(scrapy.Item):
    url = scrapy.Field()
    listing_url = scrapy.Field()

    hemnet_id = scrapy.Field()

    broker_name = scrapy.Field()
    broker_phone = scrapy.Field()
    broker_email = scrapy.Field()

    broker_firm = scrapy.Field()
    broker_firm_phone = scrapy.Field()

    sold_date = scrapy.Field()

    price_per_square_meter = scrapy.Field()
    price = scrapy.Field()
    asked_price = scrapy.Field()
    price_trend_flat = scrapy.Field()
    price_trend_percentage = scrapy.Field()

    rooms = scrapy.Field()
    monthly_fee = scrapy.Field()
    square_meters = scrapy.Field()
    cost_per_year = scrapy.Field()
    year = scrapy.Field()
    type = scrapy.Field()
    association = scrapy.Field()
    lot_size = scrapy.Field()
    biarea = scrapy.Field()

    address = scrapy.Field()
    geographic_area = scrapy.Field()

    title = scrapy.Field()
    description = scrapy.Field()
    housing_form = scrapy.Field()
    tenure = scrapy.Field()
    days_on_hemnet = scrapy.Field()
    is_new_construction = scrapy.Field()
    is_project = scrapy.Field()
    is_project_unit = scrapy.Field()
    is_upcoming = scrapy.Field()
    is_foreclosure = scrapy.Field()
    is_bidding_ongoing = scrapy.Field()
    bidding_started = scrapy.Field()
    published_at = scrapy.Field()
    times_viewed = scrapy.Field()
    verified_bidding = scrapy.Field()
    listing_broker_url = scrapy.Field()
    listing_broker_gallery_url = scrapy.Field()
    post_code = scrapy.Field()
    municipality_name = scrapy.Field()
    region_name = scrapy.Field()
    county_name = scrapy.Field()
    districts = scrapy.Field()
    labels = scrapy.Field()
    relevant_amenities = scrapy.Field()
    listing_collection_ids = scrapy.Field()
    breadcrumbs = scrapy.Field()
    ad_targeting = scrapy.Field()
    attachments = scrapy.Field()
    images = scrapy.Field()
    images_preview = scrapy.Field()
    thumbnail = scrapy.Field()
    photo_attribution = scrapy.Field()
    price_change = scrapy.Field()
    upcoming_open_houses = scrapy.Field()
    floor_plan_images = scrapy.Field()
    video_attachment = scrapy.Field()
    three_d_attachment = scrapy.Field()
    energy_classification = scrapy.Field()
    active_package = scrapy.Field()
    seller_package_recommendation = scrapy.Field()
    housing_cooperative = scrapy.Field()
    housing_cooperative_name = scrapy.Field()
    yearly_arrende_fee = scrapy.Field()
    yearly_leasehold_fee = scrapy.Field()
    land_area = scrapy.Field()
    formatted_land_area = scrapy.Field()
    formatted_living_area = scrapy.Field()
    formatted_supplemental_area = scrapy.Field()
    supplemental_area = scrapy.Field()
    formatted_floor = scrapy.Field()
    closest_water_distance_meters = scrapy.Field()
    coastline_distance_meters = scrapy.Field()
    raw_listing = scrapy.Field()
    raw_apollo_state = scrapy.Field()
    broker_raw = scrapy.Field()
    broker_agency_raw = scrapy.Field()
    main_image_url = scrapy.Field()
    main_image_bytes = scrapy.Field()
    main_image_mime = scrapy.Field()
    floorplan_image_url = scrapy.Field()
    floorplan_image_bytes = scrapy.Field()
    floorplan_image_mime = scrapy.Field()


class HemnetCompItem(scrapy.Item):
    url = scrapy.Field()
    
    hemnet_id = scrapy.Field()
    salda_id = scrapy.Field()

    lattitude = scrapy.Field()
    longitude = scrapy.Field()

    city = scrapy.Field()
    postal_city = scrapy.Field()
    district = scrapy.Field()
    country = scrapy.Field()
    region = scrapy.Field()
    municipality = scrapy.Field()
    street = scrapy.Field()

    offers_selling_price = scrapy.Field()
    living_area = scrapy.Field()
    rooms = scrapy.Field()
    cost_per_year = scrapy.Field()
    new_production = scrapy.Field()
    broker_firm = scrapy.Field()
    upcoming_open_houses = scrapy.Field()
    location = scrapy.Field()
    home_swapping = scrapy.Field()
    has_price_change = scrapy.Field()
    status = scrapy.Field()
    price = scrapy.Field()
    monthly_fee = scrapy.Field()
    main_location = scrapy.Field()
    publication_date = scrapy.Field()
    has_active_toplisting = scrapy.Field()
    images_count = scrapy.Field()
    item_type = scrapy.Field()
    price_per_m2 = scrapy.Field()
    street_address = scrapy.Field()
